name: "Package Desktop App - Dev"

on:
  workflow_dispatch:

jobs:
  check-app-dev-workflows:
    name: Lints workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash) 1.6.22
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} -color .github/workflows/package-app-dev.yml
        shell: bash

  package-dev:
    environment: development
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        shell: bash
        run: yarn install --immutable
      - name: Run common build
        shell: bash
        run: yarn common build
      - name: Run extension install deps
        shell: bash
        run: yarn extension
      - name: Build desktop ui
        shell: bash
        run: yarn app build:ui:lavamoat:ci
      - name: Build desktop app
        shell: bash
        run: yarn app build:app
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          METAMASK_ENVIRONMENT: 'development'
      - name: Package app for ${{ matrix.os }}
        shell: bash
        run:  |
              if [ "$RUNNER_OS" == "Linux" ]; then
                yarn app package:linux:ci -p never
              elif [ "$RUNNER_OS" == "Windows" ]; then
                yarn app package:win:ci -p never
              elif [ "$RUNNER_OS" == "macOS" ]; then
                yarn app package:mac -p never
              else
                echo "$RUNNER_OS not supported"
                exit 1
              fi
        env:
          WIN_CSC_LINK: ${{ secrets.MMD_WIN_CERT_BASE64_DEV }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.MMD_WIN_CERT_PASSWORD_DEV }}
          CSC_LINK: ${{ secrets.MMD_MAC_CSC_BASE64_DEV }}
          CSC_KEY_PASSWORD: ${{ secrets.MMD_MAC_CSC_KEY_PASSWORD_DEV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Persist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packaged-apps
          path: |
            packages/app/packages/*.dmg
            packages/app/packages/*.AppImage
            packages/app/packages/*.exe
